---
AWSTemplateFormatVersion: 2010-09-09


Description: >
  Cloudformation template for continuous testing pipeline.

Parameters:
  GitHubUser:
    Type: String
    Default: github_username
    Description: Your username on GitHub.

  GitHubToken:
    Type: String
    Default: github_token
    NoEcho: true
    Description: >
      Token for the user specified above. (https://github.com/settings/tokens)

  GitHubRepo:
    Type: String
    Default: github_repository
    Description: The repo name of the sample service.

  GitHubBranch:
    Type: String
    Default: master
    Description: The branch of the repo to continuously deploy.

  FrontendGitHubRepo:
    Type: String
    Default: github_repository
    Description: The repo name of the frontend service.

  FrontendGitHubBranch:
    Type: String
    Default: master
    Description: The branch of the frontend repo to continuously deploy.

  TemplateBucket:
    Type: String
    Default: gt-backend-pipeline
    Description: >
      The S3 bucket from which to fetch the templates used by this stack.

  #  DatabaseHost:
  #    Type: String
  #    Description: Hostname for database
  #
  #  DatabaseName:
  #    Type: String
  #    Default: postgres
  #    Description: Name of database
  #
  #  DatabaseUsername:
  #    Type: String
  #    Description: Username for database
  #
  #  DatabasePassword:
  #    NoEcho: true
  #    Type: String
  #    Description: Password for database
  #
  #  Auth0ClientID:
  #    NoEcho: true
  #    Type: String
  #    Description: Auth0 client id
  #
  #  Auth0ClientSecret:
  #    NoEcho: true
  #    Type: String
  #    Description: Auth0 client secret
  #
  #  Auth0APIBaseURL:
  #    NoEcho: true
  #    Type: String
  #    Description: Auth0 base API

  FlaskSessionSecret:
    NoEcho: true
    Type: String
    Description: Flask session secret

Metadata:
  AWS::CloudFormation::Interface:
    ParameterLabels:
      GitHubUser:
        default: "User"
      GitHubRepo:
        default: "Repo"
      GitHubBranch:
        default: "Branch"
      GitHubToken:
        default: "Personal Access Token"
    ParameterGroups:
      - Label:
          default: GitHub Configuration
        Parameters:
          - GitHubRepo
          - GitHubBranch
          - GitHubUser
          - GitHubToken
      - Label:
          default: Stack Configuration
        Parameters:
          - TemplateBucket

Resources:
  DynamoDB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/module-dynamodb.yaml"

  Secrets:
    Type: AWS::CloudFormation::Stack
    DependsOn: DynamoDB
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/module-secrets-manager.yaml"
      Parameters:
        #        DatabaseHost: !Ref DatabaseHost
        DatabaseName: !GetAtt DynamoDB.Outputs.TableName
        #        DatabaseUsername: !Ref DatabaseUsername
        #        DatabasePassword: !Ref DatabasePassword
        #        Auth0ClientID: !Ref Auth0ClientID
        #        Auth0ClientSecret: !Ref Auth0ClientSecret
        #        Auth0APIBaseURL: !Ref Auth0APIBaseURL
        FlaskSessionSecret: !Ref FlaskSessionSecret

  Cluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/module-ecs-cluster.yaml"

  FrontendCluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/module-ecs-cluster.yaml"

  ECR:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/module-ecr.yaml"

  FrontendECR:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/module-ecr.yaml"

  DeploymentPipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/module-deployment-pipeline.yaml"
      Parameters:
        Cluster: !GetAtt Cluster.Outputs.ClusterName
        Service: !GetAtt Service.Outputs.Service
        GitHubUser: !Ref GitHubUser
        GitHubToken: !Ref GitHubToken
        GitHubRepo: !Ref GitHubRepo
        GitHubBranch: !Ref GitHubBranch
        Repository: !GetAtt ECR.Outputs.Repository
        DBCredentialsARN: !GetAtt Secrets.Outputs.DBCredentialsARN
        Auth0SecretsARN: !GetAtt Secrets.Outputs.Auth0SecretsARN
        FlaskSecretsARN: !GetAtt Secrets.Outputs.FlaskSecretsARN

  FrontendDeploymentPipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/module-frontend-deployment-pipeline.yaml"
      Parameters:
        Cluster: !GetAtt FrontendCluster.Outputs.ClusterName
        Service: !GetAtt FrontendService.Outputs.Service
        GitHubUser: !Ref GitHubUser
        GitHubToken: !Ref GitHubToken
        GitHubRepo: !Ref FrontendGitHubRepo
        GitHubBranch: !Ref FrontendGitHubBranch
        Repository: !GetAtt FrontendECR.Outputs.Repository

  LoadBalancer:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/module-load-balancer.yaml"
      Parameters:
        Subnets: !GetAtt VPC.Outputs.Subnets
        VpcId: !GetAtt VPC.Outputs.VpcId

  FrontendLoadBalancer:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/module-load-balancer.yaml"
      Parameters:
        Subnets: !GetAtt VPC.Outputs.Subnets
        VpcId: !GetAtt VPC.Outputs.VpcId

  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/module-vpc.yaml"
      Parameters:
        Name: !Ref AWS::StackName
        VpcCIDR: 10.215.0.0/16
        Subnet1CIDR: 10.215.10.0/24
        Subnet2CIDR: 10.215.20.0/24

  Service:
    Type: AWS::CloudFormation::Stack
    DependsOn: DynamoDB
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/module-service.yaml"
      Parameters:
        Cluster: !GetAtt Cluster.Outputs.ClusterName
        TargetGroup: !GetAtt LoadBalancer.Outputs.TargetGroup
        SourceSecurityGroup: !GetAtt LoadBalancer.Outputs.SecurityGroup
        Subnets: !GetAtt VPC.Outputs.Subnets
        Repository: !GetAtt ECR.Outputs.Repository
        DBCredentialsARN: !GetAtt Secrets.Outputs.DBCredentialsARN
        Auth0SecretsARN: !GetAtt Secrets.Outputs.Auth0SecretsARN
        FlaskSecretsARN: !GetAtt Secrets.Outputs.FlaskSecretsARN
        DynamoDBName: !GetAtt DynamoDB.Outputs.TableName

  FrontendService:
    Type: AWS::CloudFormation::Stack
    DependsOn: DynamoDB
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/module-frontend-service.yaml"
      Parameters:
        Cluster: !GetAtt FrontendCluster.Outputs.ClusterName
        TargetGroup: !GetAtt FrontendLoadBalancer.Outputs.TargetGroup
        SourceSecurityGroup: !GetAtt FrontendLoadBalancer.Outputs.SecurityGroup
        Subnets: !GetAtt VPC.Outputs.Subnets
        Repository: !GetAtt FrontendECR.Outputs.Repository

Outputs:
  WebAppUrl:
    Description: The sample service that is being continuously deployed.
    Value: !GetAtt FrontendLoadBalancer.Outputs.ServiceUrl

  ServiceUrl:
    Description: The sample service that is being continuously deployed.
    Value: !GetAtt LoadBalancer.Outputs.ServiceUrl

  PipelineUrl:
    Description: The continuous deployment pipeline in the AWS Management Console.
    Value: !GetAtt DeploymentPipeline.Outputs.PipelineUrl
