AWSTemplateFormatVersion: '2010-09-09'
Resources:
  DDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "session_id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "session_id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
Outputs:
  TableName:
    Value: !Ref 'DDBTable'
    Description: Table name of the newly created DynamoDB table
