---
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  DatabaseHost:
    Type: String
    Default: ''
  DatabaseName:
    Type: String
    Default: ''
  DatabaseUsername:
    Type: String
    Default: ''
  DatabasePassword:
    NoEcho: true
    Type: String
    Default: ''
  Auth0ClientID:
    NoEcho: true
    Type: String
    Default: ''
  Auth0ClientSecret:
    NoEcho: true
    Type: String
    Default: ''
  Auth0APIBaseURL:
    NoEcho: true
    Type: String
    Default: ''
  FlaskSessionSecret:
    NoEcho: true
    Type: String
    Default: ''


Resources:
  DBCredentials:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: DatabaseCredentials
      Description: Login DB Credentials to Database
      SecretString:
        !Join
        - ''
        - - "{\"db_username\":\""
          - !Ref DatabaseUsername
          - "\",\"db_password\":\""
          - !Ref DatabasePassword
          - "\",\"db_host\":\""
          - !Ref DatabaseHost
          - "\",\"db_name\":\""
          - !Ref DatabaseName
          - "\"}"
  Auth0Secrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: Auth0Secrets
      Description: Secrets for Auth0
      SecretString:
        !Join
        - ''
        - - "{\"client_id\":\""
          - !Ref Auth0ClientID
          - "\",\"client_secret\":\""
          - !Ref Auth0ClientSecret
          - "\",\"api_base_url\":\""
          - !Ref Auth0APIBaseURL
          - "\"}"
  FlaskSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: FlaskSecrets
      Description: Secrets for Flask
      SecretString:
        !Join
        - ''
        - - "{\"secret_key\":\""
          - !Ref FlaskSessionSecret
          - "\"}"
Outputs:
  DBCredentialsARN:
    Value: !Sub ${DBCredentials}
  Auth0SecretsARN:
    Value: !Sub ${Auth0Secrets}
  FlaskSecretsARN:
    Value: !Sub ${FlaskSecrets}
